server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: spring-core-demo
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1